### PR TITLE
Included 2D materials in doc

### PR DESCRIPTION
**Pull request by xin-flex**

### CODE REVIEW

**Comment by tylerflex** [comment]
Looks good! I just tested and it rendered correctly. @caseyflex  the reference seems to not show up in Graphene

image

**Review by tylerflex — APPROVED** [review]

**Review by caseyflex — APPROVED** [review]
Looks great. See this PR for docstring fixes:

https://github.com/flexcompute/tidy3d/pull/799

**Comment by momchil-flex** [comment]
@xin-flex when you sign off on Casey's PR we can merge that one and this one.

**Comment by xin-flex** [comment]
> @xin-flex when you sign off on Casey's PR we can merge that one and this one.

Just did.

**Pull request merged**
