### PR TITLE
Faq update

### PR DESCRIPTION
**Pull request by e-g-melo**
Hi Tom. I've updated and included the divergence troubleshooting in the FAQ. I don't know why, but the documentation didn't mount on my computer. Could you please, take a look at it to see if everything renders correctly?

### CODE REVIEW

**Comment by tomflexcompute** [comment]
Thanks @e-g-melo for the update. Currently the capitalization for "How to Troubleshoot a Diverged FDTD Simulation" is a bit inconsistent with other titles. Could you change it to "How to troubleshoot a diverged FDTD simulation" in both the faq.rst and DivergedFDTDSimulation.ipynb?

When you say "the documentation didn't mount on my computer", do you mean you tried to build the docs but it didn't work?

**Comment by e-g-melo** [comment]
Thanks Tom! Yes, I’ve tried to build it, and it didn't work in my computer.

**Review by tomflexcompute — APPROVED** [review]
I can't build it either due to some pydantic related error. Nonetheless I think it should be fine. After merging into develop, we can see the build in readthedocs to make sure it looks correct before merging develop to latest branch, which is used for production.

**Comment by e-g-melo** [comment]
I've updated the files and will merge them to develop. Thanks again! Let's see if it will work!

**Pull request merged**
