### PR TITLE
feat: custom sitemap and robots

### PR DESCRIPTION
**Pull request by Lius-fe**

### CODE REVIEW

**Review by tylerflex — COMMENTED** [review]
This looks fine to me, I guess the two things are:
1. this hardcodes the mapping between stable, latest and the branches? so if we want to change this in the future, we will need to change the readthedocs config and this conf.py code?
2. this branch built successfully on readthedocs? Just want to ensure before we move it into production.

Thanks

**Comment by tylerflex** [comment]
I put a guide to readthedocs building [here](https://github.com/flexcompute-readthedocs/tidy3d-docs/wiki/Testing-feature-branches-on-readthedocs). I tested the site and it looks ok to me, thanks!

**Comment by lius-magic** [comment]
> This looks fine to me, I guess the two things are:
> 
> 1. this hardcodes the mapping between stable, latest and the branches? so if we want to change this in the future, we will need to change the readthedocs config and this conf.py code?
> 2. this branch built successfully on readthedocs? Just want to ensure before we move it into production.
> 
> Thanks

Q1:  if there are changes to the branch mapping, we need to update the conf.py file. 
Q2: This branch has not been built yet. I think it is necessary to thoroughly test this branch before entering production.

**Comment by tylerflex** [comment]
Ok sounds good, I just triggered a build:
https://readthedocs.com/projects/flexcompute-tidy3ddocumentation/builds/1496085/

And put some more instructions in the readthedocs

**Comment by lius-magic** [comment]
I am not allowed to access readthedocs.com.

**Comment by tylerflex** [comment]
I put the login information in the Lark page, just pinged you in a comment on lark

**Comment by tylerflex** [comment]
If the site looks good, let me know and I'll merge this into develop and then latest.

**Comment by lius-magic** [comment]
I ran the tests and the output files look good, but there's an issue with the paths. Please give me a moment to debug.

**Comment by Lius-fe** [comment]
> If the site looks good, let me know and I'll merge this into develop and then latest.

hi Tyler,
I'm so sorry that this PR has been blocked for so long. You can merge it into the develop branch and then the latest at any time.

**Pull request merged**
