### PR TITLE
Updated Fitting notebook to showcase new FastDispersionFitter

### PR DESCRIPTION
**Pull request by caseyflex**

### CODE REVIEW

**Comment by momchil-flex** [comment]
Great. I would suggest removing the DispersionFitter completely. Too often we get divergence because of active materials.

On the other hand, how about expanding the fast fitter section a bit, specifically with more tips or illustrations on using some of the advanced parameters? If you can think of something that may be commonly of use (e.g. when fitting metals? or some difficult models)

**Review by weiliangjin2021 — APPROVED** [review]
Looks very good to me!

**Comment by tylerflex** [comment]
@momchil-flex feel free to merge this if your comments are addressed.

**Comment by momchil-flex** [comment]
Looks great now, I think this will be super useful going forward.

**Pull request merged**
