### PR TITLE
Added custom medium tutorial notebook

### PR DESCRIPTION
**Pull request by tomflexcompute**
Hi @weiliangjin2021 @dbochkov-flexcompute could you do a quick review on the custom medium tutorial? To run the notebook, add the following lines after tidy3d import:

`from tidy3d.web.config import DEFAULT_CONFIG`
`DEFAULT_CONFIG.solver_version = "pml-22.2.6"`

### CODE REVIEW

**Comment by weiliangjin2021** [comment]
Few additional edits in api.rst:

- Add `CustomMedium` below "Non-Dispersive Medium"
- Add `PermittivityDataset` below "Individual Datasets"

**Review by dbochkov-flexcompute — APPROVED** [review]
Very cool! just a few minor comments: 
- can `ScalarFieldDataArray` and `PermittivityDataset` be imported simply as:
```
from tidy3d import ScalarFieldDataArray
from tidy3d import PermittivityDataset
```
or referred to as `td.ScalarFieldDataArray` and  `td.PermittivityDataset`?
- is there any analytical expression that predicts (even if approximately) the focus distance of such a lens?
- btw, should it be called gradient index lens instead of graded?

**Comment by weiliangjin2021** [comment]
> (a) The custom medium is only evaluated within the geometry of the structure, but this extrapolation is for points within the volume of the geometry that are not within the supplied data points?

Correct.

> (b) How is this extrapolation performed? So if “nearest”, I guess it just chooses the value of the nearest coordinate? But for “interp”, does it interpolate between the nearest coordinates?

The extrapolation method is the same as the interp_method. So it can be nearest or linear. Internally, xarray is using [interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d). The parameter related to extrapolation is `fill_value`, which is set to be "extrapolate" in custom medium's interp.

**Comment by tomflexcompute** [comment]
> 

Thanks for the comments. For the class method links, I suppose td.CustomMedium.from_nk will have the link `https://docs.flexcompute.com/projects/tidy3d/en/pre190/_autosummary/tidy3d.CustomMedium.html#tidy3d.CustomMedium.fron_nk`? Is `pre190` correct?

**Comment by tylerflex** [comment]
I actually don't know if it will be `pre190` or `pre/1.9.0`. I assume the latter. We can fix it later if it breaks.

**Comment by tomflexcompute** [comment]
Thanks @dbochkov-flexcompute @tylerflex @weiliangjin2021 for reviewing. The changes have been made in the current version. I can double check if the links work properly for the 1.9 pre release later and fix them if anything is wrong.

**Review by weiliangjin2021 — APPROVED** [review]

**Pull request merged**
