### PR TITLE
Updating FAQ section

### PR DESCRIPTION
**Pull request by momchil-flex**
- Added new section on normalization
- Updated sections on units, divergence, and dispersive materials
- Removed section on PML as it was quite stale, and we warn about putting structures exactly at boundaries now

### CODE REVIEW

**Comment by momchil-flex** [comment]
I want to discuss tomorrow how to normalize PointDipole.

**Review by tylerflex — COMMENTED** [review]
Looks good. Just a note that we have a couple front end issues from a while ago about adding discussions to the docs / faq: 
1. [discussion of auto shutoff](https://github.com/flexcompute/tidy3d/issues/199)
2. [information about PML parameters](https://github.com/flexcompute/tidy3d/issues/135)
I'm not sure how important these are to include, but maybe this is a good time to either add a bit of info on each, or just decide to close those issues.

**Comment by tylerflex** [comment]
For example, it could be nice to document exactly how the `field_decay` value is computed over time.

**Comment by momchil-flex** [comment]
I added two more sections on early shutoff and on not long enough run time. I think the PML parameters is a bit involved/advanced and maybe not needed at this point (probably fine to close the issue too).

**Comment by momchil-flex** [comment]
@xin-flex would you like to take a look?

**Pull request merged**
