### PR TITLE
Added photonic crystal filter notebook

### PR DESCRIPTION
**Pull request by tomflexcompute**
Hi @weiliangjin2021 could you give this photonic crystal waveguide mode filter a quick review? Thanks!

### CODE REVIEW

**Comment by weiliangjin2021** [comment]
Very good! A few comments:
- x/y/z coordinates are mentioned below Cell 4, but not defined in the schematic. Wonder if it can be added in the figure.
- When defining the waveguide, it appears to me that you can just define a single waveguide of length td.inf along x-direction. The part inside the PhC will be overridden by the holes if the holes are added the last.

**Review by weiliangjin2021 — APPROVED** [review]

**Comment by tomflexcompute** [comment]
Thanks for the helpful comments. The notebook has been revised, in case you want to take another look. Will merge it later today.

**Comment by tomflexcompute** [comment]
@tylerflex this PR is ready to merge into develop, but since we opened a new branch for pre release, I wonder if we should merge this into the pre release branch instead?

**Comment by tylerflex** [comment]
does it work with 1.8.2? if so, I can just push it to readthedocs and make it public now?

**Comment by tomflexcompute** [comment]
> does it work with 1.8.2? if so, I can just push it to readthedocs and make it public now?

Yes, it does not depend on any new features so in principle can be published as it is now.

**Pull request merged**
