### PR TITLE
Move anisotropic medium to dispersive list

### PR DESCRIPTION
**Pull request by weiliangjin2021**

### CODE REVIEW

**Comment by tylerflex** [comment]
Hm, maybe the distinction between "Dispersive Media" and "Non-Dispersive Media" should be rethought, because it seems to me that AnisotropicMedium doesn't really fit into either because it can be either dispersive or non-dispersive. Maybe we should include a new category that covers a medium that is a combination of other media. For now, perhaps we call this "anisotropic media"?

## Non-Dispersive Media
* Medium
* PEC

## Dispersive Media
* Lorentz
...

## Anisotropic Media
* AnisotropicMedia
* (Medium2D)

What do you think?

**Comment by weiliangjin2021** [comment]
Where does CustomMedium fit in that case? Perhaps in the catogary "anisotropic medium", but add a note that it's dispersiveless?

**Comment by tylerflex** [comment]
Hm, maybe either in anisotropic media or we could rename that section "Other Mediums"?

**Comment by tylerflex** [comment]
sounds good to me

**Comment by weiliangjin2021** [comment]
sounds good to me as well

**Comment by tylerflex** [comment]
implemented in #120

**Pull request closed without merging**
