### PR TITLE
fixes for 1.9.0rc2

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Comment by tylerflex** [comment]
merge with front end PR https://github.com/flexcompute/tidy3d/pull/684

**Comment by tylerflex** [comment]
To do:
- [ ] Review my subsection ordering and make appropriate changes.
- [ ] Add subsections for case studies (@tomflexcompute, maybe later?)
- [ ] Figure out inherited properties, no good solutions yet.

**Comment by momchil-flex** [comment]
I think subsections are fine, but now there's a merge conflict with Weiliang's poly slab commit. The new example there can be put in the advanced structure definitions.

**Comment by tylerflex** [comment]
sounds good, should I do the rebase or do you want to?

**Comment by momchil-flex** [comment]
you can do it

**Pull request merged**
