### PR TITLE
add pre-release adjoint tutorials

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Review by tomflexcompute — COMMENTED** [review]
Hi @tylerflex . Seems like tutorials #3 and #4 are still in progress? I have attached some typos I found so far. Will take a look after all notebooks are complete. 

[review doc.docx](https://github.com/flexcompute-readthedocs/tidy3d-docs/files/10538370/review.doc.docx)

**Comment by tylerflex** [comment]
Thanks @tomflexcompute , yes 3 and 4 are undergoing some changes. I'll fix them up the next couple days. Appreciate your review!

**Comment by tylerflex** [comment]
@tomflexcompute , I made all the changes you suggested. Thanks a lot. (I need to get some spell checker for Jupiter notebooks. Do you have one that you like?)

**Review by weiliangjin2021 — APPROVED** [review]

**Comment by tylerflex** [comment]
closing because #109 does this without merge conflicts

**Pull request closed without merging**
