### PR TITLE
Title and metadata revision for SEO

### PR DESCRIPTION
**Pull request by tomflexcompute**
Second round of title and metadata revision for SEO on the marketing site per Zongfu's suggestions. He wants to move the Tidy3D Introduction notebooks from under Examples tab to Start Here tab. @tylerflex do you know how to change it? 

Built locally and everything looks fine.

### CODE REVIEW

**Comment by tylerflex** [comment]
Hm, this is a bit confusing, so the "tabs" including `StartHere` are defined in the `index.rst` [page](https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/develop/docs/source/index.rst).

Right now `quickstart.rst` contains the `StartHere` page.  I think what we would need to do is make something like `start_here.rst` similar to `examples.rst` and then put `quickstart.rst` and our other notebooks in there.

So something like

```
# index.rst
Tidy3D Documentation
====================

Tidy3D is a software package for solving extremely large electrodynamics problems using the finite-difference time-domain (FDTD) method.

This is the documentation for the python API, which is the main way to build simulation models, submit jobs, and analyze results of completed runs.

.. toctree::
   :maxdepth: 1
   :caption: User Guide

   start_here
   examples
   faq
   howdoi
   api
   changelog

.. image:: _static/ring_resonator.png
   :width: 1200

```

```
# start_here.rst
Start Here
========

.. toctree::
    :maxdepth: 1
	
    quickstart
    notebooks/StartHere
    ...
```

and probably we should change the # Title of the quickstart from "Start Here" to "Installation Instructions" or "Set Up"?

maybe give that a try?

**Comment by tomflexcompute** [comment]
Thanks @tylerflex for the instruction. I think it works.

**Review by tylerflex — APPROVED** [review]
looks good to me, feel free to merge.

**Comment by tomflexcompute** [comment]
Thanks @tylerflex for reviewing. If the docs are built fine, I'll propagate the commit to latest and readthedocs. The new titles on the tutorial notebooks are a bit long but hopefully the layout still looks nice.

**Comment by tomflexcompute** [comment]
Actually there are a few notebooks (at least two from what I can see) that will be merged into develop soon. Let's propagate the commits to latest and readthedocs after they are merged.

**Comment by tylerflex** [comment]
Sounds good. I will just stay hands off here and give you the authority to merge PRs and make whatever changes are necessary.  The end goal will just be to have any PRs with new feature notebooks merged into pre/2.3 and then get everything else into latest with the SEO tags. We also need to figure out what to do about the MC related PRS 194 and 206. I dont know if they need those merged.

**Pull request merged**
