### PR TITLE
Inclusion of resonance finder tutorial.

### PR DESCRIPTION
**Pull request by e-g-melo**
Basic tutorial about resonance finder to include in Python "Tutorial" section.

I've updated the SEO information for the Symmetry notebook as well.

### CODE REVIEW

**Comment by tomflexcompute** [comment]
Thanks @flexcompute-readthedocs . Could you also fix the following issue found by MC?
image

**Review by tomflexcompute — APPROVED** [review]
Very nice tutorial that is easy to read and follow! Thanks @e-g-melo for another contribution. Would be very useful for users who are interested in high Q cavities. A few additional thoughts:

- "at the simulation boundaries" -> "within the simulation domain"? 

- “waiting for the fields completely decay” -> "waiting for the fields to completely decay"

- This seems like a good opportunity to use plot_3d(). Could you try it and see if the 3D plot looks good in this case?

Maybe @caseyflex can take a quick look as well?

**Comment by tomflexcompute** [comment]
By the way, could you try to build the docs locally to see if the diverged simulation troubleshooting guide looks fine?

**Comment by caseyflex** [comment]
These look really helpful, thanks! A couple comments:

DivergedFDTDSimulation:
- "Gain Medium from Fitting" -- I think we recommend the FastDispersionFitter, which enforces passive fits. Can we link to this here as the recommended option?

ResonanceFinder:
- the comment about shutoff=0 is a bit confusing as the simulation will never run for longer than run_time; the shutoff option allows for early shutoff in the case of field decay.
- Before cell 7: " to certify " -> ", and certify"
- Cell 9: I usually like to plot the fourier transform of this signal as well, so you can confirm the resonant frequencies visually. Something like:
```
time_response = sim_data["monitor_time_0"].Ez.squeeze()
freq_response = np.fft.ifft(time_response)
freqs = np.linspace(0, 1/sim_data.simulation.dt, len(time_response))
plot_inds = np.where((freq_range[0] < freqs) & (freqs < freq_range[1]))
plt.figure()
plt.plot(freqs[plot_inds], freq_response[plot_inds])
```

**Comment by e-g-melo** [comment]
Hi @tomflexcompute and @caseyflex! Thanks for reviewing the notebook. I've changed the points you have mentioned.
Tom, I've transformed the DivergedFDTDSimulation.md file into a Python notebook to make sure it will render correctly. When migrating the FAQ to the learning center I will mount it and see if the .md files will render properly.

**Comment by tomflexcompute** [comment]
> Hi @tomflexcompute and @caseyflex! Thanks for reviewing the notebook. I've changed the points you have mentioned. Tom, I've transformed the DivergedFDTDSimulation.md file into a Python notebook to make sure it will render correctly. When migrating the FAQ to the learning center I will mount it and see if the .md files will render properly.

Thank you very much Emerson. Feel free to merge the PR.

**Pull request merged**
