### PR TITLE
Adding two-photon absorption and others to api.rst

### PR DESCRIPTION
**Pull request by caseyflex**
This adds the following to api.rst:

NonlinearModel
TwoPhotonAbsorption
KerrNonlinearity
ContinuousWave
CustomSourceTime

### CODE REVIEW

**Comment by tylerflex** [comment]
I forget (feel free to correct me) we probably dont want to support `ContinuousWave` officially? since it doesn't ramp down I think it can have weird effects in the frequency-domain monitors? Maybe @momchil-flex remembers. If that's the case, let's leave it uncommented.

**Comment by momchil-flex** [comment]
I think I'm fine with supporting it officially, just let's add to the documentation that field decay will not happen, so the user should note that the simulation will run for the full `run_time`, and the normalization of frequency-domain monitors will be arbitrary.

**Comment by tylerflex** [comment]
can we merge this?

**Comment by caseyflex** [comment]
After TPA is merged, frontend and backend

**Comment by tylerflex** [comment]
oh right, of course 🤦 thought it was just something we forgot to merge for a second.

**Pull request merged**
