### PR TITLE
Updated Docs

### PR DESCRIPTION
**Pull request by tomflexcompute**
- A new installation instruction is added to the quickstart.rst; 

- Example notebooks are reordered in examples.rst so notebooks of similar category are listed together. For example, PIC examples, plasmonics examples, etc. I think it could make it easier for users to locate the examples they are looking for.

- Hyperlinks are fixed in metasurface and y junction notebooks; 

- Fixing one heading level in the waveguide crossing notebook.

### CODE REVIEW

**Review by xin-flex — APPROVED** [review]
aside from a minor edit, looks good to me

**Comment by tomflexcompute** [comment]
Thanks @xin-flex for reviewing. If @tylerflex thinks the changes are all good, feel free to merge.

**Review by tylerflex — APPROVED** [review]
Thanks Tom. 

Just a note that some of our users (including Casey) have had some issues installing tidy3d using Conda environments. I think virtualenv is possibly safer although maybe a little less convenient. If you verify that the conda installation instructions here work, then that's fine though, we can leave it as it will be useful for people who have perhaps not used python environments before.

**Comment by tomflexcompute** [comment]
Thanks @tylerflex  for reviewing. I think if someone follows the instructions from scratch, it should work. I tested on my desktop and laptop, which are both Windows machines so I can't speak for other OS. Exactly as you said, this guide is mainly for people with little experience.

**Pull request merged**
